steps:
  - id: build-training-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.training
      - --tag
      - ${_DEPLOY_IMAGE}
      - .

images:
  - ${_DEPLOY_IMAGE}

timeout: 1200s
